version: '3.8'

services: 
	mysql:
     image: mysql:8.0
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
	  ports:
	    - "3306:3306"
	  volumes:
	    - db_data:/var/lib/mysql
	  
	   app:
	      build:
	        context: .
	      container_name: java_app
	      environment:
	        SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/mydb
	        SPRING_DATASOURCE_USERNAME: myuser
	        SPRING_DATASOURCE_PASSWORD: mypassword
	      depends_on:
	        - database
	      ports:
	        - "8080:8080"
			
			prometheus:
			    image: prom/prometheus
			    volumes:
			      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
			    networks:
			      - localprom
			    ports:
			      - 9090:9090
			networks:
			  localprom:
			    driver: bridge

volumes:
	db_data:

